### ISSUE TITLE
still supposed to work?

### ISSUE THREAD

**Issue by mschulze0** [lsgs/redcap-autoschedule#1]
Hi,

is this module still supposed to work on new REDCap versions? It doesn't seem to be doing anything anymore. I've never used it before, so not sure how I would normally be able to tell if it's working correctly. Curiously there are no errors popping up, it's just not doing anything it seems.

**Comment by lsgs** [comment]
Yes @mschulze0 - it's still working for me. We have 9.7.8 in Production and I'm using 10.0.3 in my dev environment. It's hard to say why it's not working for you without a bit more info.

**Comment by mschulze0** [comment]
hi @lsgs 
REDCap version is 10.0.0. Will create a new project and try it out there. As mentioned there are no errors or warnings (not even in the console), it just doesn't create a schedule. Not sure what else you need to know?

**Comment by mschulze0** [comment]
@lsgs i think i just selected the wrong variable which had a slightly different name from the one where I was entering the date...it's working fine now!

**Comment by mschulze0** [comment]
@lsgs do you think it would be possible to modify the module in such a way that would start the scheduling beginning only with the event where the date was entered that triggered the auto-schedule? when you do the auto-scheduling with a date in an event that isn't the first event, it doesn't really make sense to go back and start the schedule with that date for the first event. instead what i would expect is that the schedule starts with the event I entered the date in.

**Comment by lsgs** [comment]
I'm glad it's working for you as designed, @mschulze0. Your suggestion is a good one though and it would make intuitive sense for it to work that way. It would mean subtracting the event's offset days from the base date prior to using it in the schedule generation insert query.
