### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by sarasorrell** [lsgs/redcap-autoschedule#2]
I just found this and could really use it in a project I'm working on. I've tried configuring a survey date field, but nothing is happening with the calendar or schedule. Does anyone know where I can find more instructions on how to use this mod? Thanks!

**Comment by lsgs** [comment]
Yes @sarasorrell this external module is still fully functional. Look at the external module configuration dialog after activating the module in your project for a description of the options available - or indeed check out the readme.md page here!

The main idea is that you can select a date or datetime validated text field to use as the baseline date for your records schedules.
